"""Valid node `type` strings accepted by the platform DAG validator.

Mirrors the backend node registry. A type outside this list is rejected with
`"type": "must be a valid value"`, so the CLI checks flows against it and suggests
the closest match instead of letting you find out from a 400.
"""

NODE_TYPES: dict[str, tuple[str, ...]] = {
    "agents": (
        "dynamiq.nodes.agents.Agent",
        "dynamiq.nodes.agents.orchestrators.GraphAgentManager",
        "dynamiq.nodes.agents.orchestrators.GraphOrchestrator",
        "dynamiq.nodes.agents.orchestrators.GraphState",
    ),
    "audio": (
        "dynamiq.nodes.audio.ElevenLabsSTS",
        "dynamiq.nodes.audio.ElevenLabsTTS",
        "dynamiq.nodes.audio.WhisperSTT",
    ),
    "converters": (
        "dynamiq.nodes.converters.CSVConverter",
        "dynamiq.nodes.converters.DOCXFileConverter",
        "dynamiq.nodes.converters.ExcelFileConverter",
        "dynamiq.nodes.converters.HTMLConverter",
        "dynamiq.nodes.converters.LLMImageConverter",
        "dynamiq.nodes.converters.LLMPDFConverter",
        "dynamiq.nodes.converters.MultiFileTypeConverter",
        "dynamiq.nodes.converters.PPTXFileConverter",
        "dynamiq.nodes.converters.PyPDFConverter",
        "dynamiq.nodes.converters.TextFileConverter",
        "dynamiq.nodes.converters.UnstructuredFileConverter",
    ),
    "detectors": (
        "dynamiq.nodes.detectors.LlamaGuardDetector",
        "dynamiq.nodes.detectors.PIIDetector",
        "dynamiq.nodes.detectors.PromptInjectionDetector",
    ),
    "embedders": (
        "dynamiq.nodes.embedders.BedrockDocumentEmbedder",
        "dynamiq.nodes.embedders.BedrockTextEmbedder",
        "dynamiq.nodes.embedders.CohereDocumentEmbedder",
        "dynamiq.nodes.embedders.CohereTextEmbedder",
        "dynamiq.nodes.embedders.GeminiDocumentEmbedder",
        "dynamiq.nodes.embedders.GeminiTextEmbedder",
        "dynamiq.nodes.embedders.HuggingFaceDocumentEmbedder",
        "dynamiq.nodes.embedders.HuggingFaceTextEmbedder",
        "dynamiq.nodes.embedders.MistralDocumentEmbedder",
        "dynamiq.nodes.embedders.MistralTextEmbedder",
        "dynamiq.nodes.embedders.OpenAIDocumentEmbedder",
        "dynamiq.nodes.embedders.OpenAITextEmbedder",
        "dynamiq.nodes.embedders.VertexAIDocumentEmbedder",
        "dynamiq.nodes.embedders.VertexAITextEmbedder",
        "dynamiq.nodes.embedders.WatsonXDocumentEmbedder",
        "dynamiq.nodes.embedders.WatsonXTextEmbedder",
    ),
    "extractors": (
        "dynamiq.nodes.extractors.ByIndexExtractor",
        "dynamiq.nodes.extractors.ByRegexExtractor",
        "dynamiq.nodes.extractors.FileTypeExtractor",
    ),
    "images": (
        "dynamiq.nodes.images.ImageEdit",
        "dynamiq.nodes.images.ImageGeneration",
        "dynamiq.nodes.images.ImageVariation",
    ),
    "knowledge_graphs": (
        "dynamiq.nodes.knowledge_graphs.KnowledgeGraphEntityExtractor",
        "dynamiq.nodes.knowledge_graphs.KnowledgeGraphRetriever",
        "dynamiq.nodes.knowledge_graphs.KnowledgeGraphWriter",
    ),
    "knowledgebases": (
        "dynamiq.nodes.knowledgebases.DynamiqKnowledgebaseGraphSearch",
        "dynamiq.nodes.knowledgebases.DynamiqKnowledgebaseHybridSearch",
        "dynamiq.nodes.knowledgebases.DynamiqKnowledgebaseVectorSearch",
    ),
    "llms": (
        "dynamiq.nodes.llms.AI21",
        "dynamiq.nodes.llms.Anthropic",
        "dynamiq.nodes.llms.Anyscale",
        "dynamiq.nodes.llms.AzureAI",
        "dynamiq.nodes.llms.Bedrock",
        "dynamiq.nodes.llms.Cerebras",
        "dynamiq.nodes.llms.Cohere",
        "dynamiq.nodes.llms.CustomLLM",
        "dynamiq.nodes.llms.Databricks",
        "dynamiq.nodes.llms.DeepInfra",
        "dynamiq.nodes.llms.DeepSeek",
        "dynamiq.nodes.llms.FireworksAI",
        "dynamiq.nodes.llms.Gemini",
        "dynamiq.nodes.llms.Groq",
        "dynamiq.nodes.llms.HuggingFace",
        "dynamiq.nodes.llms.Mistral",
        "dynamiq.nodes.llms.NvidiaNIM",
        "dynamiq.nodes.llms.OpenAI",
        "dynamiq.nodes.llms.OpenRouter",
        "dynamiq.nodes.llms.Perplexity",
        "dynamiq.nodes.llms.Replicate",
        "dynamiq.nodes.llms.SambaNova",
        "dynamiq.nodes.llms.TogetherAI",
        "dynamiq.nodes.llms.VertexAI",
        "dynamiq.nodes.llms.WatsonX",
        "dynamiq.nodes.llms.xAI",
    ),
    "operators": (
        "dynamiq.nodes.operators.Choice",
        "dynamiq.nodes.operators.Map",
        "dynamiq.nodes.operators.Pass",
    ),
    "rankers": (
        "dynamiq.nodes.rankers.CohereReranker",
        "dynamiq.nodes.rankers.LLMDocumentRanker",
        "dynamiq.nodes.rankers.TimeWeightedDocumentRanker",
    ),
    "retrievers": (
        "dynamiq.nodes.retrievers.ChromaDocumentRetriever",
        "dynamiq.nodes.retrievers.ElasticsearchDocumentRetriever",
        "dynamiq.nodes.retrievers.KnowledgebaseRetriever",
        "dynamiq.nodes.retrievers.MilvusDocumentRetriever",
        "dynamiq.nodes.retrievers.OpenSearchDocumentRetriever",
        "dynamiq.nodes.retrievers.PGVectorDocumentRetriever",
        "dynamiq.nodes.retrievers.PineconeDocumentRetriever",
        "dynamiq.nodes.retrievers.QdrantDocumentRetriever",
        "dynamiq.nodes.retrievers.VectorStoreRetriever",
        "dynamiq.nodes.retrievers.WeaviateDocumentRetriever",
    ),
    "splitters": (
        "dynamiq.nodes.splitters.AutoSplitter",
        "dynamiq.nodes.splitters.CodeSplitter",
        "dynamiq.nodes.splitters.ContextualSplitter",
        "dynamiq.nodes.splitters.DocumentSplitter",
        "dynamiq.nodes.splitters.HTMLHeaderSplitter",
        "dynamiq.nodes.splitters.HTMLSectionSplitter",
        "dynamiq.nodes.splitters.MarkdownHeaderSplitter",
        "dynamiq.nodes.splitters.RecursiveCharacterSplitter",
        "dynamiq.nodes.splitters.RecursiveJsonSplitter",
        "dynamiq.nodes.splitters.SemanticSplitter",
        "dynamiq.nodes.splitters.TokenSplitter",
    ),
    "storages": ("dynamiq.nodes.storages.WeaviateVectorStore",),
    "tools": (
        "dynamiq.nodes.tools.CuaDesktopTool",
        "dynamiq.nodes.tools.CypherExecutor",
        "dynamiq.nodes.tools.DaytonaInterpreterTool",
        "dynamiq.nodes.tools.E2BDesktopTool",
        "dynamiq.nodes.tools.E2BInterpreterTool",
        "dynamiq.nodes.tools.ExaTool",
        "dynamiq.nodes.tools.FirecrawlSearchTool",
        "dynamiq.nodes.tools.FirecrawlTool",
        "dynamiq.nodes.tools.HttpApiCall",
        "dynamiq.nodes.tools.HumanFeedbackTool",
        "dynamiq.nodes.tools.JinaScrapeTool",
        "dynamiq.nodes.tools.JinaSearchTool",
        "dynamiq.nodes.tools.MCPServer",
        "dynamiq.nodes.tools.Pipedream",
        "dynamiq.nodes.tools.Python",
        "dynamiq.nodes.tools.PythonCodeExecutor",
        "dynamiq.nodes.tools.SQLExecutor",
        "dynamiq.nodes.tools.ScaleSerpTool",
        "dynamiq.nodes.tools.Stagehand",
        "dynamiq.nodes.tools.TavilyTool",
        "dynamiq.nodes.tools.ThinkingTool",
        "dynamiq.nodes.tools.ZenRowsTool",
    ),
    "transformers": (
        "dynamiq.nodes.transformers.AnyToJSON",
        "dynamiq.nodes.transformers.JSONToAny",
        "dynamiq.nodes.transformers.TextTemplate",
    ),
    "utils": (
        "dynamiq.nodes.utils.Input",
        "dynamiq.nodes.utils.Output",
    ),
    "validators": (
        "dynamiq.nodes.validators.RegexMatch",
        "dynamiq.nodes.validators.ValidChoices",
        "dynamiq.nodes.validators.ValidJSON",
        "dynamiq.nodes.validators.ValidPython",
    ),
    "writers": (
        "dynamiq.nodes.writers.ChromaDocumentWriter",
        "dynamiq.nodes.writers.ElasticsearchDocumentWriter",
        "dynamiq.nodes.writers.MilvusDocumentWriter",
        "dynamiq.nodes.writers.OpenSearchDocumentWriter",
        "dynamiq.nodes.writers.PGVectorDocumentWriter",
        "dynamiq.nodes.writers.PineconeDocumentWriter",
        "dynamiq.nodes.writers.QdrantDocumentWriter",
        "dynamiq.nodes.writers.VectorStoreWriter",
        "dynamiq.nodes.writers.WeaviateDocumentWriter",
    ),
}

ALL_NODE_TYPES: frozenset[str] = frozenset(t for group in NODE_TYPES.values() for t in group)
