import io

from dynamiq.connections import E2B
from dynamiq.nodes.agents.react import ReActAgent
from dynamiq.nodes.llms import Anthropic as AnthropicLLM
from dynamiq.nodes.tools.e2b_sandbox import E2BInterpreterTool
from dynamiq.nodes.types import InferenceMode
from dynamiq.utils.logger import logger

AGENT_ROLE = """
Senior Data Scientist and Programmer with the ability to write well-structured Python code.
You have access to Python tools and the web to search for the best solutions to problems.
Generally, you follow these rules:
    - ALWAYS FORMAT YOUR RESPONSE IN MARKDOWN.
    - Use double quotes for property names.
    - Ensure the code is correct and runnable; reiterate if it does not work.
"""

PROMPT = """
Read the data, and create markdown file - formatted with osme analysis.
"""

FILE_PATH = "./data/house_prices.csv"

FILE_DESCRIPTION = f"""
- The file is `{FILE_PATH}`.
- The CSV file uses a comma (`,`) as the delimiter.
- It contains the following columns (examples included):
    - bedrooms: number of bedrooms
    - bathrooms: number of bathrooms
    - price: price of a house
"""


def read_file_as_bytesio(file_path: str, filename: str = None, description: str = None) -> io.BytesIO:
    """
    Reads the content of a file and returns it as a BytesIO object with custom attributes for filename and description.

    Args:
        file_path (str): The path to the file.
        filename (str, optional): Custom filename for the BytesIO object.
        description (str, optional): Custom description for the BytesIO object.

    Returns:
        io.BytesIO: The file content in a BytesIO object with custom attributes.
    """
    with open(file_path, "rb") as f:
        file_content = f.read()

    file_io = io.BytesIO(file_content)

    file_io.name = filename if filename else "uploaded_file.csv"
    file_io.description = description if description else "No description provided"

    return file_io


def create_agent():
    """
    Create and configure the agent with necessary tools.

    Returns:
        ReActAgent: A configured Dynamiq ReActAgent ready to run.
    """
    import os
    os.environ["ANTHROPIC_API_KEY"] = os.getenv("ANTHROPIC_API_KEY_DYN")
    tool = E2BInterpreterTool(connection=E2B())
    llm = AnthropicLLM(
        name="claude",
        model="claude-sonnet-4-20250514",
        temperature=1,
        max_tokens=32000,
        thinking_enabled=True,
        budget_tokens=4000,
    )

    agent_software = ReActAgent(
        name="Agent",
        llm=llm,
        tools=[tool],
        role=AGENT_ROLE,
        max_loops=10,
        inference_mode=InferenceMode.XML,
    )

    return agent_software


def run_workflow(prompt: str, files_to_upload: list[io.BytesIO]) -> tuple[str, dict, dict]:
    """
    Main function to set up and run the workflow, handling any exceptions that may occur.

    Args:
        prompt (str): Question/task for the agent to accomplish.
        files_to_upload (List[io.BytesIO]): A list of BytesIO objects representing files to upload.

    Returns:
        tuple[str, dict, dict]: The content generated by the agent, intermediate steps, and any files generated.
    """
    try:
        agent = create_agent()

        result = agent.run(
            input_data={"input": prompt, "files": files_to_upload},
        )

        content = result.output.get("content")
        intermediate_steps = result.output.get("intermediate_steps", {})
        files = result.output.get("files", {})

        return content, intermediate_steps, files
    except Exception as e:
        logger.error(f"An error occurred: {e}")
        return "", {}, {}


if __name__ == "__main__":
    import base64
    import os

    csv_file_io = read_file_as_bytesio(
        file_path=FILE_PATH, filename=FILE_PATH.split("/")[-1], description=FILE_DESCRIPTION
    )

    output, steps, files = run_workflow(prompt=PROMPT, files_to_upload=[csv_file_io])

    logger.info("---------------------------------Result-------------------------------------")
    logger.info(output)

    if files:
        logger.info("\n---------------------------------Generated Files-------------------------------------")
        logger.info(f"Agent generated {len(files)} file(s):")

        output_dir = "./agent_outputs"
        os.makedirs(output_dir, exist_ok=True)

        for file_path, file_content in files.items():
            file_name = file_path.split('/')[-1]

            try:
                file_data = base64.b64decode(file_content)
                output_path = os.path.join(output_dir, file_name)

                with open(output_path, 'wb') as f:
                    f.write(file_data)

                logger.info(f"  ✓ Saved: {file_name} ({len(file_data):,} bytes) -> {output_path}")
            except Exception as e:
                logger.error(f"  ✗ Failed to save {file_name}: {e}")
