from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.units import inch


def run(params=None, helpers=None, **context):
    """
    Generate a comprehensive PDF report with multiple sections.

    Args:
        params: Dictionary with parameters:
            - title: Report title (default: "Sample Report")
            - subtitle: Report subtitle
            - author: Author name
            - date: Report date
            - sections: List of content sections
            - data_table: Optional data for table

    Returns:
        dict: Result with file_path and status
    """
    # Extract parameters
    title = params.get("title", "Sample Report")
    subtitle = params.get("subtitle", "Generated by Dynamiq Document Creator")
    author = params.get("author", "Dynamiq Agent")
    report_date = params.get("date", "")
    sections = params.get("sections", [
        {
            "title": "Introduction",
            "content": "This is a sample report demonstrating PDF generation capabilities."
        },
        {
            "title": "Analysis",
            "content": "This section contains the main analysis and findings."
        },
        {
            "title": "Conclusion",
            "content": "Summary of key points and recommendations."
        }
    ])
    data_table = params.get("data_table", None)

    # Create PDF
    pdf_path = "sample_report.pdf"
    doc = SimpleDocTemplate(pdf_path, pagesize=letter)
    story = []

    # Styles
    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor=colors.HexColor('#2c3e50'),
        spaceAfter=30,
        alignment=1  # Center
    )
    heading_style = styles['Heading2']
    normal_style = styles['Normal']

    # Title
    story.append(Paragraph(title, title_style))
    story.append(Paragraph(subtitle, styles['Normal']))
    story.append(Spacer(1, 0.2 * inch))

    # Metadata
    metadata = f"<b>Author:</b> {author}"
    if report_date:
        metadata += f" | <b>Date:</b> {report_date}"
    story.append(Paragraph(metadata, normal_style))
    story.append(Spacer(1, 0.5 * inch))

    # Sections
    for section in sections:
        section_title = section.get("title", "")
        section_content = section.get("content", "")

        # Section heading
        story.append(Paragraph(section_title, heading_style))
        story.append(Spacer(1, 0.1 * inch))

        # Section content
        story.append(Paragraph(section_content, normal_style))
        story.append(Spacer(1, 0.3 * inch))

    # Optional data table
    if data_table:
        story.append(Paragraph("Data Summary", heading_style))
        story.append(Spacer(1, 0.1 * inch))

        # Create table
        table = Table(data_table)
        table.setStyle(TableStyle([
            # Header row
            ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
            ('FONTSIZE', (0, 0), (-1, 0), 12),
            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),

            # Data rows
            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
            ('GRID', (0, 0), (-1, -1), 1, colors.black),
            ('FONTNAME', (0, 1), (-1, -1), 'Helvetica'),
            ('FONTSIZE', (0, 1), (-1, -1), 10),
            ('PADDING', (0, 0), (-1, -1), 6),
        ]))

        story.append(table)

    # Build PDF
    doc.build(story)

    # Save to FileStore
    with open(pdf_path, 'rb') as f:
        helpers['write_file']('reports/sample_report.pdf', f.read())

    return {
        "status": "success",
        "file_path": "reports/sample_report.pdf",
        "message": f"PDF report '{title}' created successfully with {len(sections)} sections"
    }


# Example usage (for testing):
if __name__ == "__main__":
    # Mock helpers for standalone testing
    class MockHelpers:
        def write_file(self, path, content):
            with open(path.split('/')[-1], 'wb') as f:
                f.write(content)
            print(f"File saved: {path}")

    sample_params = {
        "title": "Q4 2024 Sales Report",
        "subtitle": "Comprehensive Analysis of Sales Performance",
        "author": "Sales Analytics Team",
        "date": "January 2025",
        "sections": [
            {
                "title": "Executive Summary",
                "content": "Q4 2024 showed strong growth with revenue "
                "increasing by 25% year-over-year. "
                "Key highlights include expansion "
                "into new markets and successful product launches.",
            },
            {
                "title": "Key Metrics",
                "content": "Total revenue: $5.2M | New customers: 342 "
                "| Customer retention: 94% | Average deal size: $15,200",
            },
            {
                "title": "Regional Performance",
                "content": "North America led with $2.8M in revenue, followed by "
                "Europe at $1.6M and Asia-Pacific at $0.8M. "
                "All regions showed positive growth trends.",
            },
            {
                "title": "Recommendations",
                "content": "Continue investment in top-performing regions, "
                "increase marketing spend in emerging markets, "
                "and focus on customer retention programs.",
            },
        ],
        "data_table": [
            ["Region", "Revenue", "Growth", "Customers"],
            ["North America", "$2.8M", "+30%", "156"],
            ["Europe", "$1.6M", "+22%", "98"],
            ["Asia-Pacific", "$0.8M", "+18%", "88"],
        ]
    }

    result = run(params=sample_params, helpers={'write_file': MockHelpers().write_file})
    print(result)
