"""A check written before the rule vocabulary grew keeps the outcome it had, unless a documented change says why.

Each table pairs a check in the old vocabulary, where `X` stands for the value under test, with a shape of that value,
and pins the finding origin/main (294b2941) gave: its status and message, generated by running the same node there.
Where this branch answers otherwise, the row is `Changed`, holding main's outcome, this branch's and the documented
change behind the difference; every other row must match main exactly. A shape is a literal value of `doc.x`, the key
left out (`ABSENT`), a value the check reads as meant (`VALID`), or a derived value nobody could compute
(`DERIVED_ERROR`: `d = doc.n / doc.zero` over a zero). The differential fuzz behind the change covers the breadth;
this is the part a reader can scan.
"""

from typing import NamedTuple

import pytest

from dynamiq.nodes.operators import Rules
from dynamiq.nodes.types import DerivedValue, NamedField, Rule
from dynamiq.runnables import RunnableConfig, RunnableStatus

# The documented changes a row may differ from main by.
MORE_DATE_FORMATS = "date() reads more formats"
BLANK_DATE_IS_MISSING = "a blank date is missing"
UNREADABLE_OVER_MISSING = "an unreadable value is named over a missing one"
DERIVED_ERRORS_SURFACE = "a derived value's error surfaces"
CHANGES = (MORE_DATE_FORMATS, BLANK_DATE_IS_MISSING, UNREADABLE_OVER_MISSING, DERIVED_ERRORS_SURFACE)

ABSENT = "<absent>"
VALID = "<valid>"
DERIVED_ERROR = "<derived error>"
SHAPES = [ABSENT, None, "", "  ", "TBD", VALID, DERIVED_ERROR]

# The value each check reads as meant.
VALID_VALUES = {
    "has(X)": "a",
    "X is defined": "a",
    "X is none": "a",
    "X | float > 1": "5",
    "X | trim == 'a'": " a ",
    "days_between(X, doc.y) > 0": "2026-03-01",
    "days_between(X, doc.z) > 0": "2026-03-01",
    "days_between(date(X), date(doc.z)) > 0": "2026-03-01",
    "date(X | replace('/', '-')) > date('2020-01-01')": "2026/03/01",
    "date(X) < date('2027-01-01')": "Mar 1, 2026",
    "twice > 1": 5,
    "has(X) and X > 1": 5,
    "not has(X) or X > 1": 5,
}

DIVISION_BY_ZERO = "check could not be evaluated: division by zero"
TEXT_OVER_A_NUMBER = "check could not be evaluated: '>' not supported between instances of 'str' and 'int'"


class Changed(NamedTuple):
    """A row this branch answers otherwise than main did, and the documented change that says why."""

    main: tuple[str, str | None]
    now: tuple[str, str | None]
    change: str


# Under the node's default policy, `not_evaluated`.
UNDER_NOT_EVALUATED = {
    "has(X)": {
        ABSENT: ("fail", None),
        None: ("fail", None),
        "": ("pass", None),
        "  ": ("pass", None),
        "TBD": ("pass", None),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(("fail", None), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
    "X is defined": {
        ABSENT: ("fail", None),
        None: ("pass", None),
        "": ("pass", None),
        "  ": ("pass", None),
        "TBD": ("pass", None),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(("pass", None), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
    "X is none": {
        ABSENT: ("fail", None),
        None: ("pass", None),
        "": ("fail", None),
        "  ": ("fail", None),
        "TBD": ("fail", None),
        VALID: ("fail", None),
        DERIVED_ERROR: Changed(("pass", None), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
    "X | float > 1": {
        ABSENT: ("not_evaluated", "missing value for doc.x"),
        None: ("not_evaluated", "missing value for doc.x"),
        "": ("fail", None),
        "  ": ("fail", None),
        "TBD": ("fail", None),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for d"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "X | trim == 'a'": {
        ABSENT: ("not_evaluated", "missing value for doc.x"),
        None: ("not_evaluated", "missing value for doc.x"),
        "": ("fail", None),
        "  ": ("fail", None),
        "TBD": ("fail", None),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for d"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "days_between(X, doc.y) > 0": {
        ABSENT: ("not_evaluated", "missing value for doc.x"),
        None: ("not_evaluated", "missing value for doc.x"),
        "": ("not_evaluated", "check could not be evaluated: not a date: ''"),
        "  ": ("not_evaluated", "check could not be evaluated: not a date: '  '"),
        "TBD": ("not_evaluated", "check could not be evaluated: not a date: 'TBD'"),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for d"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "days_between(X, doc.z) > 0": {
        ABSENT: ("not_evaluated", "missing value for doc.x"),
        None: ("not_evaluated", "missing value for doc.x"),
        "": ("not_evaluated", "check could not be evaluated: not a date: 'later'"),
        "  ": ("not_evaluated", "check could not be evaluated: not a date: 'later'"),
        "TBD": ("not_evaluated", "check could not be evaluated: not a date: 'later'"),
        VALID: ("not_evaluated", "check could not be evaluated: not a date: 'later'"),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for d"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "days_between(date(X), date(doc.z)) > 0": {
        ABSENT: ("not_evaluated", "missing value for doc.x"),
        None: ("not_evaluated", "missing value for doc.x"),
        "": Changed(
            ("not_evaluated", "check could not be evaluated: not a date: ''"),
            ("not_evaluated", "check could not be evaluated: not a date: 'later'"),
            UNREADABLE_OVER_MISSING,
        ),
        "  ": Changed(
            ("not_evaluated", "check could not be evaluated: not a date: '  '"),
            ("not_evaluated", "check could not be evaluated: not a date: 'later'"),
            UNREADABLE_OVER_MISSING,
        ),
        "TBD": ("not_evaluated", "check could not be evaluated: not a date: 'TBD'"),
        VALID: ("not_evaluated", "check could not be evaluated: not a date: 'later'"),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for d"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "date(X | replace('/', '-')) > date('2020-01-01')": {
        ABSENT: ("not_evaluated", "missing value for doc.x"),
        None: ("not_evaluated", "missing value for doc.x"),
        "": Changed(
            ("not_evaluated", "check could not be evaluated: not a date: ''"),
            ("not_evaluated", "missing value for doc.x"),
            BLANK_DATE_IS_MISSING,
        ),
        "  ": Changed(
            ("not_evaluated", "check could not be evaluated: not a date: '  '"),
            ("not_evaluated", "missing value for doc.x"),
            BLANK_DATE_IS_MISSING,
        ),
        "TBD": ("not_evaluated", "check could not be evaluated: not a date: 'TBD'"),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for d"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "date(X) < date('2027-01-01')": {
        ABSENT: ("not_evaluated", "missing value for doc.x"),
        None: ("not_evaluated", "missing value for doc.x"),
        "": Changed(
            ("not_evaluated", "check could not be evaluated: not a date: ''"),
            ("not_evaluated", "missing value for doc.x"),
            BLANK_DATE_IS_MISSING,
        ),
        "  ": Changed(
            ("not_evaluated", "check could not be evaluated: not a date: '  '"),
            ("not_evaluated", "missing value for doc.x"),
            BLANK_DATE_IS_MISSING,
        ),
        "TBD": ("not_evaluated", "check could not be evaluated: not a date: 'TBD'"),
        VALID: Changed(
            ("not_evaluated", "check could not be evaluated: not a date: 'Mar 1, 2026'"),
            ("pass", None),
            MORE_DATE_FORMATS,
        ),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for d"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "twice > 1": {
        ABSENT: ("not_evaluated", "missing value for twice"),
        None: ("not_evaluated", "missing value for twice"),
        "": ("not_evaluated", TEXT_OVER_A_NUMBER),
        "  ": ("not_evaluated", TEXT_OVER_A_NUMBER),
        "TBD": ("not_evaluated", TEXT_OVER_A_NUMBER),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(
            ("not_evaluated", "missing value for twice"), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE
        ),
    },
    "has(X) and X > 1": {
        ABSENT: ("fail", None),
        None: ("fail", None),
        "": ("not_evaluated", TEXT_OVER_A_NUMBER),
        "  ": ("not_evaluated", TEXT_OVER_A_NUMBER),
        "TBD": ("not_evaluated", TEXT_OVER_A_NUMBER),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(("fail", None), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
    "not has(X) or X > 1": {
        ABSENT: ("pass", None),
        None: ("pass", None),
        "": ("not_evaluated", TEXT_OVER_A_NUMBER),
        "  ": ("not_evaluated", TEXT_OVER_A_NUMBER),
        "TBD": ("not_evaluated", TEXT_OVER_A_NUMBER),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(("pass", None), ("not_evaluated", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
}
# Under `fail`, the checks that answered on a derived value nobody computed.
UNDER_FAIL = {
    "has(X)": {
        ABSENT: ("fail", None),
        None: ("fail", None),
        "": ("pass", None),
        "  ": ("pass", None),
        "TBD": ("pass", None),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(("fail", None), ("fail", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
    "X is none": {
        ABSENT: ("fail", None),
        None: ("pass", None),
        "": ("fail", None),
        "  ": ("fail", None),
        "TBD": ("fail", None),
        VALID: ("fail", None),
        DERIVED_ERROR: Changed(("pass", None), ("fail", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
    "not has(X) or X > 1": {
        ABSENT: ("pass", None),
        None: ("pass", None),
        "": ("fail", TEXT_OVER_A_NUMBER),
        "  ": ("fail", TEXT_OVER_A_NUMBER),
        "TBD": ("fail", TEXT_OVER_A_NUMBER),
        VALID: ("pass", None),
        DERIVED_ERROR: Changed(("pass", None), ("fail", DIVISION_BY_ZERO), DERIVED_ERRORS_SURFACE),
    },
}


def screened(check: str, shape, policy: str) -> tuple[str, str | None]:
    """The status and message of `check` over a record whose `doc.x` takes `shape`, from the node the tables were
    generated with: `twice = X * 2` beside every check, `d` where the value under test is one nobody computed, and
    beside `doc.x` a date (`doc.y`) and text that is no date (`doc.z`)."""
    x = "d" if shape == DERIVED_ERROR else "doc.x"
    derived = [DerivedValue(name="d", expression="doc.n / doc.zero")] if shape == DERIVED_ERROR else []
    node = Rules(
        name="old",
        input_fields=[NamedField(name="doc")],
        derived_values=[*derived, DerivedValue(name="twice", expression=f"{x} * 2")],
        on_missing=policy,
        rules=[Rule(id="R", check=check.replace("X", x))],
    )
    doc = {"y": "2026-06-01", "z": "later", "n": 1, "zero": 0}
    if shape not in (ABSENT, DERIVED_ERROR):
        doc["x"] = VALID_VALUES[check] if shape == VALID else shape

    result = node.run(input_data={"doc": doc}, config=RunnableConfig(callbacks=[]))

    assert result.status == RunnableStatus.SUCCESS, result.error
    finding = result.output["findings"][0]
    return finding["status"], finding["message"]


def rows():
    for policy, table in (("not_evaluated", UNDER_NOT_EVALUATED), ("fail", UNDER_FAIL)):
        for check, outcomes in table.items():
            for shape, expected in outcomes.items():
                yield pytest.param(check, shape, policy, expected, id=f"{policy}: {check} over {shape!r}")


def test_each_table_covers_every_shape_of_each_check():
    for table in (UNDER_NOT_EVALUATED, UNDER_FAIL):
        for check, outcomes in table.items():
            assert list(outcomes) == SHAPES, check
            assert check in VALID_VALUES


@pytest.mark.parametrize(("check", "shape", "policy", "expected"), list(rows()))
def test_an_old_check_keeps_mains_outcome_unless_a_documented_change_says_why(check, shape, policy, expected):
    outcome = screened(check, shape, policy)

    if isinstance(expected, Changed):
        assert expected.change in CHANGES and expected.now != expected.main
        assert outcome == expected.now
    else:
        assert outcome == expected
