import enum


class Language(str, enum.Enum):
    """Supported language presets for code-aware and document-structure-aware splitting."""

    CPP = "cpp"
    GO = "go"
    JAVA = "java"
    KOTLIN = "kotlin"
    JS = "js"
    TS = "ts"
    PHP = "php"
    PROTO = "proto"
    PYTHON = "python"
    RST = "rst"
    RUBY = "ruby"
    RUST = "rust"
    SCALA = "scala"
    SWIFT = "swift"
    MARKDOWN = "markdown"
    LATEX = "latex"
    HTML = "html"
    SOL = "sol"
    CSHARP = "csharp"
    COBOL = "cobol"
    C = "c"
    LUA = "lua"
    PERL = "perl"
    HASKELL = "haskell"
    ELIXIR = "elixir"
    POWERSHELL = "powershell"
    VISUALBASIC6 = "visualbasic6"


_LANGUAGE_SEPARATORS: dict[Language, list[str]] = {
    Language.CPP: [
        "\nclass ",
        "\nvoid ",
        "\nint ",
        "\nfloat ",
        "\ndouble ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.GO: [
        "\nfunc ",
        "\nvar ",
        "\nconst ",
        "\ntype ",
        "\nif ",
        "\nfor ",
        "\nswitch ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.JAVA: [
        "\nclass ",
        "\npublic ",
        "\nprotected ",
        "\nprivate ",
        "\nstatic ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.KOTLIN: [
        "\nclass ",
        "\nfun ",
        "\nval ",
        "\nvar ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nwhen ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.JS: [
        "\nfunction ",
        "\nconst ",
        "\nlet ",
        "\nvar ",
        "\nclass ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        "\ndefault ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.TS: [
        "\nfunction ",
        "\nconst ",
        "\nlet ",
        "\nvar ",
        "\nclass ",
        "\ninterface ",
        "\ntype ",
        "\nenum ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        "\ndefault ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.PHP: [
        "\nfunction ",
        "\nclass ",
        "\nif ",
        "\nforeach ",
        "\nwhile ",
        "\ndo ",
        "\nswitch ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.PROTO: [
        "\nmessage ",
        "\nservice ",
        "\nenum ",
        "\noption ",
        "\nimport ",
        "\nsyntax ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.PYTHON: [
        "\nclass ",
        "\ndef ",
        "\n\tdef ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.RST: [
        "\n=+\n",
        "\n-+\n",
        "\n\\*+\n",
        "\n\n.. *\n\n",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.RUBY: [
        "\ndef ",
        "\nclass ",
        "\nif ",
        "\nunless ",
        "\nwhile ",
        "\nfor ",
        "\ndo ",
        "\nbegin ",
        "\nrescue ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.RUST: [
        "\nfn ",
        "\nconst ",
        "\nlet ",
        "\nif ",
        "\nwhile ",
        "\nfor ",
        "\nloop ",
        "\nmatch ",
        "\nconst ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.SCALA: [
        "\nclass ",
        "\nobject ",
        "\ndef ",
        "\nval ",
        "\nvar ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nmatch ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.SWIFT: [
        "\nfunc ",
        "\nclass ",
        "\nstruct ",
        "\nenum ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\ndo ",
        "\nswitch ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.MARKDOWN: [
        "\n#{1,6} ",
        "```\n",
        "\n\\*\\*\\*+\n",
        "\n---+\n",
        "\n___+\n",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.LATEX: [
        "\n\\\\chapter{",
        "\n\\\\section{",
        "\n\\\\subsection{",
        "\n\\\\subsubsection{",
        "\n\\\\begin{enumerate}",
        "\n\\\\begin{itemize}",
        "\n\\\\begin{description}",
        "\n\\\\begin{list}",
        "\n\\\\begin{quote}",
        "\n\\\\begin{quotation}",
        "\n\\\\begin{verse}",
        "\n\\\\begin{verbatim}",
        "\n\\\\begin{align}",
        "$$",
        "$",
        " ",
        "",
    ],
    Language.HTML: [
        "<body",
        "<div",
        "<p",
        "<br",
        "<li",
        "<h1",
        "<h2",
        "<h3",
        "<h4",
        "<h5",
        "<h6",
        "<span",
        "<table",
        "<tr",
        "<td",
        "<th",
        "<ul",
        "<ol",
        "<header",
        "<footer",
        "<nav",
        "<head",
        "<style",
        "<script",
        "<meta",
        "<title",
        "",
    ],
    Language.SOL: [
        "\npragma ",
        "\nusing ",
        "\ncontract ",
        "\ninterface ",
        "\nlibrary ",
        "\nconstructor ",
        "\ntype ",
        "\nfunction ",
        "\nevent ",
        "\nmodifier ",
        "\nerror ",
        "\nstruct ",
        "\nenum ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\ndo while ",
        "\nassembly ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.CSHARP: [
        "\ninterface ",
        "\nenum ",
        "\nimplements ",
        "\ndelegate ",
        "\nevent ",
        "\nclass ",
        "\nabstract ",
        "\npublic ",
        "\nprotected ",
        "\nprivate ",
        "\nstatic ",
        "\nreturn ",
        "\nif ",
        "\ncontinue ",
        "\nfor ",
        "\nforeach ",
        "\nwhile ",
        "\nswitch ",
        "\nbreak ",
        "\ncase ",
        "\nelse ",
        "\ntry ",
        "\nthrow ",
        "\nfinally ",
        "\ncatch ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.COBOL: [
        "\nIDENTIFICATION DIVISION.",
        "\nENVIRONMENT DIVISION.",
        "\nDATA DIVISION.",
        "\nPROCEDURE DIVISION.",
        "\nWORKING-STORAGE SECTION.",
        "\nLINKAGE SECTION.",
        "\nFILE SECTION.",
        "\nINPUT-OUTPUT SECTION.",
        "\nOPEN ",
        "\nCLOSE ",
        "\nREAD ",
        "\nWRITE ",
        "\nIF ",
        "\nELSE ",
        "\nMOVE ",
        "\nPERFORM ",
        "\nUNTIL ",
        "\nVARYING ",
        "\nACCEPT ",
        "\nDISPLAY ",
        "\nSTOP RUN.",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.C: [
        "\nvoid ",
        "\nint ",
        "\nfloat ",
        "\ndouble ",
        "\nstruct ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nswitch ",
        "\ncase ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.LUA: [
        "\nlocal ",
        "\nfunction ",
        "\nif ",
        "\nfor ",
        "\nwhile ",
        "\nrepeat ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.PERL: [
        "\nsub ",
        "\nmy ",
        "\nour ",
        "\nlocal ",
        "\nif ",
        "\nelsif ",
        "\nelse ",
        "\nforeach ",
        "\nfor ",
        "\nwhile ",
        "\nuntil ",
        "\ndo ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.HASKELL: [
        "\nmain :: ",
        "\nmain = ",
        "\nlet ",
        "\nin ",
        "\ndo ",
        "\nwhere ",
        "\nif ",
        "\nthen ",
        "\nelse ",
        "\ncase ",
        "\nof ",
        "\nclass ",
        "\ninstance ",
        "\nmodule ",
        "\nimport ",
        "\ndata ",
        "\ntype ",
        "\nnewtype ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.ELIXIR: [
        "\ndef ",
        "\ndefp ",
        "\ndefmodule ",
        "\ndefprotocol ",
        "\ndefmacro ",
        "\ndefmacrop ",
        "\nif ",
        "\nunless ",
        "\nwhile ",
        "\ncase ",
        "\ncond ",
        "\nwith ",
        "\nfor ",
        "\ndo ",
        "\nelse ",
        "\nend ",
        "\n|>",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.POWERSHELL: [
        "\nfunction ",
        "\nparam ",
        "\nif ",
        "\nelseif ",
        "\nelse ",
        "\nfor ",
        "\nforeach ",
        "\nwhile ",
        "\nswitch ",
        "\ntrap ",
        "\ntry ",
        "\ncatch ",
        "\nfinally ",
        "\n\n",
        "\n",
        " ",
        "",
    ],
    Language.VISUALBASIC6: [
        "\nSub ",
        "\nFunction ",
        "\nClass ",
        "\nModule ",
        "\nProperty ",
        "\nIf ",
        "\nElseIf ",
        "\nElse ",
        "\nFor ",
        "\nWhile ",
        "\nDo ",
        "\nSelect Case ",
        "\nEnd Sub",
        "\nEnd Function",
        "\nEnd Class",
        "\nEnd Module",
        "\nEnd Property",
        "\nEnd If",
        "\nNext",
        "\nLoop",
        "\nWend",
        "\nEnd Select",
        "\n\n",
        "\n",
        " ",
        "",
    ],
}


def get_separators_for_language(language: Language) -> list[str]:
    """Return the recursive separator hierarchy for a given language preset."""
    if language not in _LANGUAGE_SEPARATORS:
        raise ValueError(f"Language {language} is not supported. Choose one of {list(_LANGUAGE_SEPARATORS)}.")
    return list(_LANGUAGE_SEPARATORS[language])
