name: Publish Package

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  pipeline:
    environment: prod
    name: Publish Package
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.11.24"
          python-version: "3.13"
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ secrets.AWS_REGION }}
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Build Package
        run: uv build
      - name: Publish to AWS CodeArtifact
        run: |
          CODEARTIFACT_AUTH_TOKEN=$(aws codeartifact get-authorization-token --domain dynamiq --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --region ${{ secrets.AWS_REGION }} --query authorizationToken --output text)
          CODEARTIFACT_URL=$(aws codeartifact get-repository-endpoint --domain dynamiq --domain-owner ${{ secrets.AWS_ACCOUNT_ID }} --repository dynamiq --region ${{ secrets.AWS_REGION }} --format pypi --query repositoryEndpoint --output text)
          uv publish --publish-url "${CODEARTIFACT_URL}" --username aws --password "${CODEARTIFACT_AUTH_TOKEN}"
      - name: Publish to PyPI
        run: uv publish --token ${{ secrets.PYPI_PASSWORD }}
